### ISSUE TITLE
不建议使用自创术语

### ISSUE THREAD

**Issue by A6669** [abdulle-sabaf/cathunu-bhallifa#14]
阁下在写书的过程中，自己创作了很多术语，例如将拓扑学称之为形之外学，这会导致这本书阅读上的困难，同时如果读者将来阅读其他书籍，可能由于不熟悉通用术语导致阅读上的困难，其实大部分术语谈不上谁对谁错，例如将拓扑学称之为形之外学，看不出谁有明显优势，但是带来的交流障碍是明显的，所以建议不使用任何自创术语，都改为通用术语。
ps：我看了一下你的书，有理数这个术语你没有自创，其实有理数这个术语才是真正的误解，这个术语应该翻译成比例数。

**Comment by abdulle-sabaf** [comment]
理念不同，各自安好。谢谢建议。
