### ISSUE TITLE
思理入门P23笔误：汉语里，我 们一般使用“只有……才……”，“仅当……时，有……”等连词表达充分条件假言判断。

### ISSUE THREAD

**Issue by p0prxx** [abdulle-sabaf/cathunu-bhallifa#4]
![image](https://github.com/abdulle-sabaf/cathunu-bhallifa/assets/27276984/8cb01777-b888-4659-9a4d-39a6b0cd6b56)

应为 **汉语里，我们一般使用“只有……才……”，“仅当……时，有……”等连词表达必要条件假言判断。**

**Comment by abdulle-sabaf** [comment]
已修正:)

**Comment by abdulle-sabaf** [comment]
已修正:)
