### ISSUE TITLE
思理入门-p14疑似笔误

### ISSUE THREAD

**Issue by p0prxx** [abdulle-sabaf/cathunu-bhallifa#5]
![image](https://github.com/abdulle-sabaf/cathunu-bhallifa/assets/27276984/9e0bf350-6e13-4d02-95f2-adaa2ab8ce59)

最后应该是单肯定/否定？

**Comment by abdulle-sabaf** [comment]
已修正:)

**Comment by abdulle-sabaf** [comment]
已修正:)
